services:
  promSnmp:
    container_name: promSnmp
    image: pbranestrategy/promsnmp:0.0.4
    environment:
      - PROM_DISCOVERY_API=snmp
      - PROM_METRICS_API=snmp
      - METRICS_REPO_API=snmp
      - CACHE_STATS_RATE_MILLIS=15000
      - CACHE_EXP_MILLIS=300000
      - CACHE_ENTRY_CNT=10000
      - DISCOVERY_CRON=0 0 2 * * *
      - DISCOVERY_TZ=America/New_York
      - DISCOVERY_ON_START=true
      - COLLECTION_INTERVAL=30000
      - SERVER_PORT=8080
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    profiles:
      - snmp
