services:
  promsnmp:
    container_name: promsnmp
    image: pbranestrategy/promsnmp:0.0.1
    environment:
      - SERVER_PORT=8080
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - unsecured
      - default

networks:
  backend:
    driver: bridge
