{
 "title": "PromSNMP Interface Metrics",
 "tags": [
  "snmp",
  "promsnmp",
  "network"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(sysUpTime, instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(ifHCInOctets{instance=\"$instance\"}, ifName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput (In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval]) * 8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval]) * -8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Top 10 Interfaces by Utilization (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (rate(ifHCInOctets{instance=~\"$instance\"}[$__rate_interval]) * 8 / (ifHighSpeed{instance=~\"$instance\"} * 1000000)) * 100)",
     "legendFormat": "{{ifName}} (In)"
    }
   ]
  },
  {
   "title": "Histogram Analysis (Native Histograms)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Interface Utilization Distribution (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(interface_utilization{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  { "title": "Health & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "In Errors - {{ifName}}"
    },
    {
     "expr": "rate(ifOutErrors{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "Out Errors - {{ifName}}"
    }
   ]
  },
  {
   "title": "Interface Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "In Discards - {{ifName}}"
    },
    {
     "expr": "rate(ifOutDiscards{instance=~\"$instance\", ifName=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "Out Discards - {{ifName}}"
    }
   ]
  }
 ]
}