---
volumes:
  data-prometheus: {}
  data-grafana: {}

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v3.1.0
    environment:
      TZ: UTC
    volumes:
      - ./container-fs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - data-prometheus:/prometheus
    ports:
      - "9090:9090/tcp"

  promsnmp:
    image: local/promsnmp:0.0.2-SNAPSHOT
    build:
      context: ..
      dockerfile: ../Dockerfile
    init: true
    tty: true
    stdin_open: true
    environment:
      TZ: UTC
      SERVER_PORT: 8080
    ports:
      - "8080:8080/tcp"

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    environment:
      TZ: UTC
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - data-grafana:/var/lib/grafana
      - ./container-fs/grafana/provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000/tcp"
